// <auto-generated />
namespace Seguros.Web.FrontEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregaRelacionRequerimientoAClietne2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregaRelacionRequerimientoAClietne2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005020707300_agregaRelacionRequerimientoAClietne2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
