// <auto-generated />
namespace Seguros.Web.FrontEnd.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ad1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ad1));
        
        string IMigrationMetadata.Id
        {
            get { return "202005032252465_ad1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
