USE [SegurosWeb]
GO

INSERT INTO [dbo].[Region]([Nombre_region]) VALUES('Arica y Parinacota')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Tarapaca')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Antofagasta')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES  ('Atacama')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Coquimbo')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES  ('Valparaiso')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Region del Libertador Gral. Bernardo OHiggins')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Region del Maule')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES  ('Region de Nuble')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Region del Biobio')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Region de la Araucania')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES  ('Region de Los Rios')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Region de Los Lagos')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES  ('Region Aisen del Gral. Carlos Ibanez del Campo')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES ('Region de Magallanes y de la Antartica Chilena')
INSERT INTO [dbo].[Region] ([Nombre_region]) VALUES('Region Metropolitana de Santiago')
GO
---------------------------------
INSERT INTO [dbo].[Ciudad]([Nombre_ciudad],[region_Id]) VALUES ('Arica',1) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Camarones',1)
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Putre',1) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('General Las',1)
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Iquique',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Alto Hospicio',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pozo Almonte',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Camiña',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Colchane',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Huara',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pica',2) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Antofagasta',3)
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Mejillones',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Sierra rda',3)
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Taltal',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Calama',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ollagüe',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Pedro de Atacama',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Tocopilla',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('María Elena',3) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Copiapó',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Caldera',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Tierra Amarilla',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chañaral',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Die de Almagro',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Vallenar',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Alto del Carmen',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Freirina',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Huasco',4) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Serena',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coquimbo',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Andacollo',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Higuera',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Paiguano',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Vicuña',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Illapel',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Canela',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Vilos',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Salamanca',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ovalle',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Combarbalá',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Monte Patria',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Punitaqui',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Río Hurtado',5) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Valparaíso',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Casablanca',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Concón',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Juan Fernández',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Puchuncaví',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quintero',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Viña del Mar',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Isla de Pascua',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Andes',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Calle Larga',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Rinconada',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Esteban',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Ligua',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cabildo',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Papudo',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Petorca',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Zapallar',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quillota',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Calera',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Hijuelas',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Cruz',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Nogales',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Antonio',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Algarrobo',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cartagena',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('El Quisco',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('El Tabo',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Santo Domin',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Felipe',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Catemu',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Llaillay',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Panquehue',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Putaendo',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Santa María',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quilpué',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Limache',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Olmué',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Villa Alemana',6) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Rancagua',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Codegua',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coinco',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coltauco',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Doñihue',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Graneros',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Las Cabras',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Machalí',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Malloa',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Mostazal',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Olivar',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Peumo',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pichidegua',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quinta de Tilcoco',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ren',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Requínoa',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Vicente',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pichilemu',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Estrella',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Litueche',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Marchihue',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Navidad',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Paredones',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Fernando',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chépica',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chimbaron',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lolol',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Nancagua',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Palmilla',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Peralillo',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Placilla',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pumanque',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Santa Cruz',7) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Talca',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Constitución',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Curepto',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Empedrado',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Maule',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pelarco',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pencahue',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Río Claro',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Clemente',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Rafael',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cauquenes',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chanco',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pelluhue',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Curicó',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Hualañé',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Licantén',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Molina',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Rauco',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Romeral',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Sagrada Familia',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Teno',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Vichuquén',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Linares',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Colbún',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Longaví',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Parral',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Retiro',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Javier',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Villa Alegre',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Yerbas Buenas',8) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cobquecura',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coelemu',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ninhue',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Portezuelo',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quirihue',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ránquil',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Treguaco',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Bulnes',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chillán Viejo',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chillán',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('El Carmen',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pemuco',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pinto',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quillón',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Ignacio',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Yungay',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coihueco',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ñiquén',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Carlos',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Fabián',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Nicolás',9) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Concepción',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Concepción',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coronel',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chiguayante',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Florida',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Hualqui',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lota',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Penco',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Pedro de la Paz',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Santa Juana',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Talcahuano',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Tomé',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Hualpén',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lebu',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Arauco',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cañete',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Contulmo',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Curanilahue',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Álamos',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Tirúa',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Ángeles',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Antuco' ,10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cabrero',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Laja',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Mulchén',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Nacimiento',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Negrete',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quilaco',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quilleco',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Rosendo',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Santa Bárbara',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Tucapel',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Yumbel',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Alto Biobío',10) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Temuco',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Carahue',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cunco',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Curarrehue',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Freire',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Galvarino',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('rbea',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lautaro',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Loncoche',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Melipeuco',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Nueva Imperial',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Padre las Casas',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Perquenco',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pitrufquén',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Pucón',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Saavedra',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Teodoro Schmidt',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Toltén',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Vilcún',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Villarrica',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cholchol',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Anl',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Collipulli',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Curacautín',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ercilla',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lonquimay',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Sauces',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lumaco',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Purén',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Renaico',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Traiguén',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Victoria',11) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Valdivia',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Corral',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Lanco',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Las',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Máfil',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Mariquina',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Paillaco',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Panguipulli',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Unión',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Futrono',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Ranco',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Río Bueno',12) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Puerto Montt',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Calbuco',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cochamó',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Fresia',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Frutillar',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Los Muermos',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Llanquihue',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Maullín',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Puerto Varas',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Castro',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Ancud',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chonchi',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Curaco de Vélez',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Dalcahue',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Puqueldón',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Queilén',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quellón',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quemchi',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Quinchao',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Osorno',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Puerto Octay',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Purranque',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Puyehue',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Río Negro',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Juan de la Costa',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Pablo',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chaitén',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Futaleufú',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Hualaihué',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Palena',13) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Coihaique',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('La Verde',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Aisén',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cisnes',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Guaitecas',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cochrane',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('O’Higgins',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Tortel',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Chile Chico',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Río Ibáñez',14) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Punta Arenas',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Laguna Blanca',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Río Verde',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('San Grerio',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Cabo de Hornos (Ex Navarino)',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Antártica',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Porvenir',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Primavera',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Timaukel',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Natales',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Torres del Paine',15) 
INSERT INTO [dbo].[Ciudad] ([Nombre_ciudad],[region_Id]) VALUES('Santiago',16) 
GO
-----------------------------------------------------------------------------
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Cerrillos',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Cerro Navia',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Conchalí',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('El Bosque',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Estación Central',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Huechuraba',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Independencia',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('La Cisterna',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('La Florida',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('La Granja',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('La Pintana',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('La Reina',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Las Condes',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Lo Barnechea',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Lo Espejo',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Lo Prado',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Macul',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Maipú',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Ñuñoa',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Pedro Aguirre Cerda',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Peñalolén',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Providencia',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Pudahuel',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Quilicura',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Quinta Normal',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Recoleta',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Renca',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Santia',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('San Joaquín',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('San Miguel',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('San Ramón',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Vitacura',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Puente Alto',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Pirque',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('San José de Maipo',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Colina',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Lampa',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Tiltil',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('San Bernardo',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Buin',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Calera de Tan',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Paine',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Melipilla',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Alhué',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Curacaví',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('María Pinto',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('San Pedro',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Talagante',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('El Monte',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Isla de Maipo',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Padre Hurtado',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
INSERT INTO [dbo].[Comuna] ([Nombre_comuna],[ciudad_Id]) VALUES('Peñaflor',(Select ciu.Id from [dbo].[Ciudad] as ciu where ciu.Nombre_ciudad = 'Santiago')) 
GO
--------------------------------------------------------
INSERT INTO [dbo].[Estado]([Descripcion])VALUES('PENDIENTE')
INSERT INTO [dbo].[Estado]([Descripcion])VALUES('PROCESANDO')
INSERT INTO [dbo].[Estado]([Descripcion])VALUES('CANCELADO')
INSERT INTO [dbo].[Estado]([Descripcion])VALUES('CON ERRORES')
INSERT INTO [dbo].[Estado]([Descripcion])VALUES('CERRADO')
INSERT INTO [dbo].[Estado]([Descripcion])VALUES('APROBADO')
GO
------------------------------------------------
INSERT [dbo].[Empleado] ([Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Josefa', N'Martínez', N'Flores', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 982365147, N'Marion', N'Díaz', N'López', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 155863214, N'Martina', N'Fernández', N'Gómez', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Julia', N'Sofía', N'Martinez', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Mariel', N'Mariel', N'Daniel', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Francisco', N'Rodríguez', N'Rodríguez', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'David', N'Sánchez', N'Alzate', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Manuel', N'Rojas', N'Aguirre', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Antonio', N'Muñoz', N'Cardona', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Noa', N'Soto', N'Montoya', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Valeria', N'Silva', N'Castañeda', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
INSERT [dbo].[Empleado] ( [Rut_empleado], [Nombre], [ApellidoPat], [ApellidoMat], [Fecha_nacimiento], [Calle], [NumCalle], [Comuna], [Ciudad], [Region], [Telefono], [Email], [Rol]) VALUES ( 124567893, N'Hugo', N'Sepúlveda', N'Londoño', CAST(N'2020-05-20T00:00:00.000' AS DateTime), N'pajaros', 1245, N'Ñuñoa', N'Santiago', N'RM', 12345678, N'Algo@gmail.com', 1)
GO